### ISSUE TITLE
Interface/Class stubs for Products

### ISSUE THREAD

**Issue by 1nf0rmagician** [PHOENIXCONTACT/MORYX-Template#6]
## Background
The al/resources branch includes a project with stubs for example resources. It also provides an example for where to place interfaces for the resources in the application. The documentation for [product definitions](https://github.com/PHOENIXCONTACT/MORYX-AbstractionLayer/blob/dev/docs/articles/Products/ProductDefinition.md) includes a nice description of what products are and how to implement them. 

## Idea
I think that adding example products in the al/products branch would complement that documentation with the information on were to put them.

**Comment by Toxantron** [comment]
If you believe it or not, I didn't just think about it, I actually had product stubs on the branch and then removed them again. Considering the [product samples](https://github.com/PHOENIXCONTACT/MORYX-AbstractionLayer/tree/dev/src/Moryx.Products.Samples) of the AL a full product definition seemed redundant, especially since the samples within the AL are properly maintained and always match the current version and API. The resource examples are mostly there, because it is recommended to put them in their own project. This requires additional effort for packages and references, therefor the template stub seemed reasonable. Do you see the same benefit for an empty product definition or could we improve linking to the AL?

**Comment by 1nf0rmagician** [comment]
Ahh, ok. If it is not recommended to put them in their own project, it is not the same benefit I guess. I still think that the template would be more intuitive to use with an empty product in place to guide the developer, but I agree that one could argue that it is redundant. 

If no stub is added to the branch, maybe it would be a good thing to link a project that includes products in the [Inspirations](https://github.com/PHOENIXCONTACT/MORYX-Template/tree/al/resources#inspirations) section of the readme file. (Not recommending a new project for the products sounds like a best practice to show here)

**Comment by Toxantron** [comment]
I will prepare a products folder in the root namespace of the products branch and as soon as I consider [FarMory](/Toxantron/FarMory) ready, I will link it.

**Comment by Toxantron** [comment]
I added two empty classes and will close this when the master branches references [FarMory](/Toxantron/Farmory).

**Comment by Toxantron** [comment]
I think with the CLI, ADP and range of branches, this is no longer necessary. What do you think @1nf0rmagician ?

**Comment by 1nf0rmagician** [comment]
Yes, completely agree 👍
